name: "Testing secret on fork"
on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled

jobs:
  secret-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v2
      - name: testing
        shell: bash
        env:
         SUPER_SECRET: ${{ secrets.SUPERSECRET }}
        run: |
          touch "$SUPER_SECRET"
          echo "hai github" >> "$SUPER_SECRET"
          ls
          cat "$SUPER_SECRET"
          #update the workflow